Repository KickLabs/Kicks-Shoes, pull requests merged in 2025-06, with the labels that each got.

#37 [KICKS_27][be][feat] cloudinary config for avatar
  backend/src/config/cloudinary.js
  backend/src/controllers/authController.js
  backend/src/controllers/userController.js
  backend/src/middlewares/upload.middleware.js
  backend/src/routes/userRoutes.js
  frontend/src/components/pages/account/components/ProfileTab.jsx
Labels: feat, be

#38 [KICKS-27][be][feat] Create favourite tab and CRUD favourite
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/favouriteController.js
  backend/src/models/Favorite.js
  backend/src/models/Favourite.js
  backend/src/routes/favouriteRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/components/Sidebar.jsx
  frontend/src/components/pages/account/Account.jsx
  frontend/src/components/pages/account/components/FavouritesTab.css
  frontend/src/components/pages/account/components/FavouritesTab.jsx
  frontend/src/components/pages/dashboard/AllProducts.jsx
  frontend/src/main.jsx
  package-lock.json
  package.json
Labels: ui, feat, be

#40 [KICKS-24][BE][feat] CRUD Discount Dashboard
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/discountController.js
  backend/src/models/Discount.js
  backend/src/routes/discountRoutes.js
  backend/src/utils/cronJobs.js
  frontend/src/components/pages/dashboard/DiscountListPage.jsx
  frontend/src/components/pages/dashboard/components/TableDiscounts.jsx
  package-lock.json
  package.json
Labels: feat, be, fe

#41 [KICKS-32][BE][feat] Reward Point system be
  backend/src/app.js
  backend/src/controllers/rewardPointController.js
  backend/src/routes/rewardPointRoutes.js
  backend/uploads/avatars/avatar-1749741948843-437490771.jpg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/account/account.css
  frontend/src/components/pages/account/components/ProfileTab.jsx
  frontend/src/components/pages/account/components/RewardPointsDetail.jsx
  frontend/src/main.jsx
Labels: feat, be, fe

#43 [KICKS-30][BE][FE][feat] Handle Order Management
  .eslintrc.js
  .husky/pre-commit
  .prettierrc
  backend/src/app.js
  backend/src/controllers/orderController.js
  backend/src/models/Order.js
  backend/src/routes/orderRoutes.js
  backend/src/services/order.service.js
  frontend/src/components/common/components/Header.jsx
  frontend/src/components/common/components/OrderDetails.jsx
  frontend/src/components/common/components/OrderList.jsx
  frontend/src/components/pages/authentication/pages/LoginAdmin.jsx
  frontend/src/components/pages/dashboard/components/Header.jsx
  frontend/src/components/pages/dashboard/components/TableOrders.jsx
  frontend/src/components/pages/dashboard/components/TableUsers.jsx
  frontend/src/main.jsx
  package-lock.json
  package.json
Labels: feat, be, fe

#42 [KICKS-24][BE][Fix] Fix auto update Discount Status
  backend/package.json
  backend/src/app.js
  backend/src/models/Discount.js
  package-lock.json
Labels: fix, be

#44 [KICKS-26][KICK-34][FE][BE][feat]Create Cart API (CRUD), integrate frontend state management using Redux
  backend/src/app.js
  backend/src/controllers/cartController.js
  backend/src/routes/cartRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/cart/cartService.js
  frontend/src/components/pages/cart/cartSlice.js
  frontend/src/components/pages/cart/components/CartItemCard.jsx
  frontend/src/components/pages/cart/components/CartList.jsx
  frontend/src/components/pages/cart/components/OrderSummary.jsx
  frontend/src/components/pages/cart/pages/CartPage.jsx
  frontend/src/config/api.config.js
  frontend/src/data/cartData.js
  frontend/src/main.jsx
  frontend/src/services/axiosInstance.js
  frontend/src/store/store.js
Labels: feat, be, fe

#45 [KICK-31][BE][feat] ban/unban user
  backend/src/controllers/userController.js
  backend/src/routes/userRoutes.js
  backend/src/services/user.service.js
  frontend/src/components/pages/dashboard/UserManagementPage.jsx
  frontend/src/components/pages/dashboard/components/ProductCard.jsx
  frontend/src/components/pages/dashboard/components/TableUsers.jsx
  frontend/src/main.jsx
Labels: feat, be, fe
