Repository KickLabs/Kicks-Shoes, pull requests merged in 2025-07, with the labels that each got.

#62 [KICKS] Refactor all code BE/FE
  backend/src/app.js
  backend/src/controllers/dashboardController.js
  backend/src/controllers/feedbackController.js
  backend/src/controllers/productController.js
  backend/src/controllers/rewardPointController.js
  backend/src/controllers/storeController.js
  backend/src/controllers/vnpayController.js
  backend/src/middlewares/upload.middleware.js
  backend/src/models/Feedback.js
  backend/src/models/Report.js
  backend/src/routes/dashboardRoutes.js
  backend/src/routes/productRoutes.js
  backend/src/services/feedback.service.js
  backend/src/services/product.service.js
  backend/src/services/rewardPoint.service.js
  backend/src/templates/email.templates.js
  backend/src/utils/currency.js
  frontend/src/components/common/components/Feedback.jsx
  frontend/src/components/common/components/Header.css
  frontend/src/components/common/components/Header.jsx
  frontend/src/components/common/components/OrderDetails.jsx
  frontend/src/components/common/components/ProductDetails.jsx
  frontend/src/components/pages/account/Account.jsx
  frontend/src/components/pages/account/account.css
  frontend/src/components/pages/account/components/ReportTab.jsx
  frontend/src/components/pages/cart/components/CartItemCard.jsx
  frontend/src/components/pages/cart/components/OrderSummary.jsx
  frontend/src/components/pages/checkout/CheckOut.jsx
  frontend/src/components/pages/checkout/components/CheckOutForm.jsx
  frontend/src/components/pages/checkout/components/DeliveryOptions.jsx
  frontend/src/components/pages/checkout/components/OrderDetails.jsx
  frontend/src/components/pages/checkout/components/OrderSummary.jsx
  frontend/src/components/pages/dashboard/AdminDashboard.jsx
  frontend/src/components/pages/dashboard/DashboardLayout.jsx
  frontend/src/components/pages/dashboard/ShopDashboard.jsx
  frontend/src/components/pages/dashboard/components/BestSellers.jsx
  frontend/src/components/pages/dashboard/components/Header.jsx
  frontend/src/components/pages/dashboard/components/ProductCard.jsx
  frontend/src/components/pages/dashboard/components/TableOrders.jsx
  frontend/src/components/pages/home/pages/HomePage.jsx
  frontend/src/components/pages/listing-page/pages/ListingPage.jsx
  frontend/src/components/pages/product/components/CommentSection.jsx
  frontend/src/components/pages/product/components/ProductInfoSection.css
  frontend/src/components/pages/product/components/ProductInfoSection.jsx
  frontend/src/main.jsx
  frontend/src/utils/StringFormat.js
  frontend/src/utils/currency.js
Labels: fix, refactor, be, fe

#67 [KICKS-27][be][fix] Fix update avatar
  frontend/src/components/pages/account/components/ProfileTab.jsx
  frontend/src/services/authService.js
  frontend/src/services/axiosInstance.js
Labels: fix, be

#73 [KICKS][KICKS-APP] Update handle chat and BE Mobile App
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/chatController.js
  backend/src/controllers/orderController.js
  backend/src/controllers/userController.js
  backend/src/middlewares/auth.middleware.js
  backend/src/models/Conversation.js
  backend/src/models/Message.js
  backend/src/routes/cartRoutes.js
  backend/src/routes/chatRoutes.js
  backend/src/routes/orderRoutes.js
  backend/src/routes/userRoutes.js
  backend/src/services/chat.service.js
  backend/src/socket.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/components/ChatPage.css
  frontend/src/components/common/components/ChatPage.jsx
  frontend/src/components/common/components/ProductDetails.jsx
  frontend/src/components/pages/dashboard/DashboardLayout.jsx
  frontend/src/components/pages/dashboard/ShopDashboard.jsx
  frontend/src/main.jsx
  frontend/src/services/axiosInstance.js
Labels: feat, be, fe, App

#72 [KICKS-25][be][feat] Add Final Price
  backend/src/controllers/productController.js
  backend/src/models/Product.js
  backend/src/routes/productRoutes.js
  backend/src/services/product.service.js
  frontend/src/components/common/components/ProductCard.jsx
Labels: fix, be

#74 [KICKS] Update handle UI and BE chat feature
  backend/src/controllers/cartController.js
  backend/src/controllers/favouriteController.js
  backend/src/controllers/feedbackController.js
  backend/src/models/Cart.js
  backend/src/services/chat.service.js
  frontend/.env.example
  frontend/src/assets/images/logoavt.png
  frontend/src/components/common/components/ChatPage.css
  frontend/src/components/common/components/ChatPage.jsx
  frontend/src/components/common/components/ChatWidget.css
  frontend/src/components/common/components/ChatWidget.jsx
  frontend/src/components/layout/App.jsx
  frontend/src/services/aiChatService.js
Labels: refactor, be, fe

#76 [KICKS] Add CI/CD and deploy web
  .firebase/hosting.ZnJvbnRlbmRcZGlzdA.cache
  .firebaserc
  .gitignore
  Procfile
  backend/src/app.js
  backend/src/config/cors.config.js
  backend/src/controllers/chatController.js
  firebase.json
  frontend/.env.example
  frontend/env.production.template
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/components/ChatPage.css
  frontend/src/components/common/components/ChatPage.jsx
  frontend/src/components/common/components/ChatWidget.jsx
  frontend/src/components/pages/authentication/components/SocialButton.jsx
  frontend/src/components/pages/authentication/pages/Authenticate.css
  frontend/src/config/api.config.js
  frontend/src/services/axiosInstance.js
  scripts/deploy-all.ps1
  scripts/deploy-frontend.ps1
  scripts/set-heroku-env-template.ps1
Labels: feat, be, fe
